/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/4D BANG BRANDING.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.07, -0.03]} rotation={[0.02, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1TQ_ARD-geom"].geometry}
          material={materials._1TQ_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1TQ_ARD-geom_1"].geometry}
          material={materials._1TQ_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1TQ_ARD-geom_2"].geometry}
          material={materials._1TQ_ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/4D BANG BRANDING.gltf");
